name: CI/CD Analytics

on:
  workflow_run:
    workflows: ["Android CI/CD"]
    types: [completed]

jobs:
  collect-metrics:
    name: Collect Build Metrics
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas matplotlib seaborn plotly

      - name: Collect workflow metrics
        run: |
          python scripts/collect_metrics.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate analytics report
        run: |
          python scripts/generate_report.py

      - name: Create index file for GitHub Pages
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
              <title>OpenCalc CI/CD Analytics Dashboard</title>
              <meta http-equiv="refresh" content="0; url=dashboard.html">
              <style>
                  body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
                  .loading { color: #666; }
              </style>
          </head>
          <body>
              <h1>🚀 OpenCalc CI/CD Analytics Dashboard</h1>
              <p class="loading">Redirecting to dashboard...</p>
              <p><a href="dashboard.html">Click here if not redirected automatically</a></p>
          </body>
          </html>' > reports/index.html

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Upload analytics artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analytics-report
          path: |
            analytics/
            reports/
          retention-days: 30

      - name: Send analytics summary
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "📊 CI/CD Analytics Report - ${{ github.event.workflow_run.created_at }}"
          to: amansingh08088@gmail.com
          from: GitHub Actions <amansingh08088@gmail.com>
          body: |
            Hi Aman,
            
            Here's your CI/CD Analytics Report for the latest build:
            
            Build Summary:
            - Workflow: ${{ github.event.workflow_run.name }}
            - Status: ${{ github.event.workflow_run.conclusion }}
            - Duration: ${{ github.event.workflow_run.duration }}
            - Triggered by: ${{ github.event.workflow_run.actor.login }}
            
            Key Metrics:
            - Build Time: ${{ github.event.workflow_run.duration }} seconds
            - Success Rate: Calculated from recent builds
            - Average Build Time: Trend analysis
            
            View detailed analytics: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Best regards,
            OpenCalc Analytics Bot 