name: Android CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Artifact Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      # --- Email and Discord Notifications ---

      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "✅ Build Succeeded: ${{ github.workflow }} #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: GitHub Actions <amansingh08088@gmail.com>
          body: |
            Hi Aman,
            
            Your workflow ${{ github.workflow }} run #${{ github.run_number }} has completed successfully!
            
            Build Details:
            - Repository: ${{ github.repository }}
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            - Triggered by: ${{ github.actor }}
            
            View the full details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Best regards,
            OpenCalc CI/CD Bot

      - name: Send Discord notification on success
        if: success()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            ✅ **Build Succeeded**: ${{ github.workflow }} [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            **Repo**: `${{ github.repository }}`
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
            **By**: `${{ github.actor }}`

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "❌ Build Failed: ${{ github.workflow }} #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: GitHub Actions <amansingh08088@gmail.com>
          body: |
            Hi Aman,
            
            Your workflow ${{ github.workflow }} run #${{ github.run_number }} has failed.
            
            Build Details:
            - Repository: ${{ github.repository }}
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            - Triggered by: ${{ github.actor }}
            
            Please review the logs and resolve any issues: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Best regards,
            OpenCalc CI/CD Bot

      - name: Send Discord notification on failure
        if: failure()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            ❌ **Build Failed**: ${{ github.workflow }} [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            **Repo**: `${{ github.repository }}`
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
            **By**: `${{ github.actor }}`