name: Calculator CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Lint Check
        run: ./gradlew lint

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: app/build/reports/lint-results.html
          retention-days: 30

      - name: Send Lint Report Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "📊 Lint Report: Calculator CI/CD #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: Calculator CI/CD <amansingh08088@gmail.com>
          body: |
            📊 LINT REPORT 📊
            ==================
            
            Code Quality Analysis Results for Calculator App
            
            📋 ANALYSIS SUMMARY:
            ====================
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Build #: #${{ github.run_number }}
            Triggered by: ${{ github.actor }}
            
            🔍 WHAT'S INCLUDED IN THIS REPORT:
            ===================================
            • Code style violations and suggestions
            • Potential bugs and performance issues
            • Best practices recommendations
            • Security vulnerability checks
            • Accessibility improvements
            • Android-specific optimizations
            
            📎 ATTACHMENT:
            ===============
            The complete lint report (lint-results.html) is attached to this email.
            Open it in your browser to view the detailed analysis with:
            - File-by-file breakdown
            - Line-by-line issues
            - Severity levels (Error/Warning/Info)
            - Suggested fixes and explanations
            
            📊 View full build details:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            ---
            This is an automated lint report from Calculator CI/CD Pipeline
            Generated on: ${{ github.event.head_commit.timestamp }}
          attachments: app/build/reports/lint-results.html

  build:
    name: Build & Artifact Bundle
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      # --- Firebase App Distribution ---
      - name: Install Firebase CLI
        if: success()
        run: npm install -g firebase-tools

      - name: Upload AAB to Firebase App Distribution
        if: success()
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute app/build/outputs/bundle/release/app-release.aab \
            --app "1:111193224827:android:e8dba4f640d6014b3694de" \
            --release-notes "Automated build from CI: ${{ github.sha }}" \
            --groups "cicdtesters"

      # --- Email and Discord Notifications --

      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "🎉 BUILD SUCCESS: Calculator CI/CD #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: Calculator CI/CD <amansingh08088@gmail.com>
          body: |
            🎉 BUILD SUCCESSFUL 🎉
            ======================
            
            Calculator CI/CD Pipeline has completed successfully!
            
            📋 BUILD SUMMARY:
            =================
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            Build #: #${{ github.run_number }}
            
            ✅ WHAT HAPPENED:
            =================
            • Code quality checks passed
            • Android App Bundle (AAB) built successfully
            • App distributed to Firebase App Distribution
            • All artifacts uploaded and ready for deployment
            
            📊 View full build details:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            ---
            This is an automated notification from Calculator CI/CD Pipeline
            Generated on: ${{ github.event.head_commit.timestamp }}

      - name: Send Discord notification on success
        if: success()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🎉 **BUILD SUCCESSFUL** 🎉
            
            **Calculator CI/CD Pipeline** has completed successfully!
            
            📋 **Build Details:**
            • **Repository:** `${{ github.repository }}`
            • **Branch:** `${{ github.ref_name }}`
            • **Build #:** `#${{ github.run_number }}`
            • **Commit:** `${{ github.sha }}`
            • **Triggered by:** `${{ github.actor }}`
            
            ✅ **What was accomplished:**
            • Code quality checks passed
            • Android App Bundle (AAB) built successfully
            • App distributed to Firebase App Distribution
            • All artifacts uploaded and ready for deployment
            
            📊 **[View Full Build Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**
            
            ---
            *Automated notification from OpenCalc CI/CD Pipeline*

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "🚨 BUILD FAILED: Calculator CI/CD #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: Calculator CI/CD <amansingh08088@gmail.com>
          body: |
            🚨 BUILD FAILED 🚨
            ===================
            
            Calculator CI/CD Pipeline has encountered issues!
            
            📋 BUILD SUMMARY:
            =================
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            Build #: #${{ github.run_number }}
            
            ⚠️ ACTION REQUIRED:
            ===================
            • Review the build logs to identify the issue
            • Check for compilation errors or test failures
            • Verify all dependencies are properly configured
            • Ensure code quality standards are met
            
            🔍 Investigate build failure:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            ---
            This is an automated notification from Calculator CI/CD Pipeline
            Generated on: ${{ github.event.head_commit.timestamp }}

      - name: Send Discord notification on failure
        if: failure()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🚨 **BUILD FAILED** 🚨
            
            **Calculator CI/CD Pipeline** has encountered issues!
            
            📋 **Build Details:**
            • **Repository:** `${{ github.repository }}`
            • **Branch:** `${{ github.ref_name }}`
            • **Build #:** `#${{ github.run_number }}`
            • **Commit:** `${{ github.sha }}`
            • **Triggered by:** `${{ github.actor }}`
            
            ⚠️ **Action Required:**
            • Review build logs to identify the issue
            • Check for compilation errors or test failures
            • Verify all dependencies are properly configured
            • Ensure code quality standards are met
            
            🔍 **[Investigate Build Failure](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**
            
            ---
            *Automated notification from OpenCalc CI/CD Pipeline*
