name: Android CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Artifact Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

  publish:
    name: Publish to Play Store
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/

      - name: Build Signed Release Bundle
        run: ./gradlew bundleRelease

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
          packageName: com.cyberknightsolutions.calculator
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }} 