name: Android CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Artifact Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "✅ Build Succeeded: ${{ github.workflow }} #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: GitHub Actions <amansingh08088@gmail.com>
          content_type: text/html
          body: |
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Build Success</title>
            </head>
            <body style="font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f4f4f4;">
                <div style="max-width: 600px; margin: 0 auto; background-color: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
                    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center;">
                        <h1 style="color: white; margin: 0; font-size: 24px;">🎉 Build Succeeded!</h1>
                    </div>
                    
                    <div style="padding: 30px;">
                        <div style="text-align: center; margin-bottom: 20px;">
                            <img src="https://cdn-icons-png.flaticon.com/512/190/190411.png" alt="Success" width="64" style="display: inline-block;">
                        </div>
                        
                        <p style="font-size: 16px; color: #333; margin-bottom: 20px;">Hi Aman,</p>
                        
                        <p style="font-size: 14px; color: #666; line-height: 1.6;">
                            Your workflow <strong>${{ github.workflow }}</strong> run <strong>#${{ github.run_number }}</strong> has completed <span style="color: #2e7d32; font-weight: bold;">successfully</span>!
                        </p>
                        
                        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 6px; margin: 20px 0;">
                            <h3 style="margin-top: 0; color: #333;">Build Details:</h3>
                            <ul style="color: #666; line-height: 1.8;">
                                <li><strong>Repository:</strong> ${{ github.repository }}</li>
                                <li><strong>Branch:</strong> ${{ github.ref_name }}</li>
                                <li><strong>Commit:</strong> ${{ github.sha }}</li>
                                <li><strong>Triggered by:</strong> ${{ github.actor }}</li>
                            </ul>
                        </div>
                        
                        <div style="text-align: center; margin: 30px 0;">
                            <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" 
                               style="display: inline-block; padding: 12px 24px; background-color: #2e7d32; color: white; text-decoration: none; border-radius: 6px; font-weight: bold;">
                                View Workflow Run
                            </a>
                        </div>
                        
                        <p style="font-size: 14px; color: #666; margin-top: 30px;">
                            Best regards,<br>
                            <strong>OpenCalc CI/CD Bot</strong>
                        </p>
                    </div>
                    
                    <div style="background-color: #f8f9fa; padding: 20px; text-align: center; border-top: 1px solid #eee;">
                        <p style="margin: 0; color: #888; font-size: 12px;">
                            <img src="https://cdn-icons-png.flaticon.com/512/5968/5968705.png" alt="Android" width="20" style="vertical-align: middle;"> 
                            Powered by GitHub Actions
                        </p>
                    </div>
                </div>
            </body>
            </html>

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "❌ Build Failed: ${{ github.workflow }} #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: GitHub Actions <amansingh08088@gmail.com>
          content_type: text/html
          body: |
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Build Failed</title>
            </head>
            <body style="font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f4f4f4;">
                <div style="max-width: 600px; margin: 0 auto; background-color: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
                    <div style="background: linear-gradient(135deg, #ff6b6b 0%, #ee5a52 100%); padding: 30px; text-align: center;">
                        <h1 style="color: white; margin: 0; font-size: 24px;">❌ Build Failed</h1>
                    </div>
                    
                    <div style="padding: 30px;">
                        <div style="text-align: center; margin-bottom: 20px;">
                            <img src="https://cdn-icons-png.flaticon.com/512/463/463612.png" alt="Failure" width="64" style="display: inline-block;">
                        </div>
                        
                        <p style="font-size: 16px; color: #333; margin-bottom: 20px;">Hi Aman,</p>
                        
                        <p style="font-size: 14px; color: #666; line-height: 1.6;">
                            Your workflow <strong>${{ github.workflow }}</strong> run <strong>#${{ github.run_number }}</strong> has <span style="color: #c62828; font-weight: bold;">failed</span>.
                        </p>
                        
                        <div style="background-color: #fff3f3; padding: 20px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #c62828;">
                            <h3 style="margin-top: 0; color: #333;">Build Details:</h3>
                            <ul style="color: #666; line-height: 1.8;">
                                <li><strong>Repository:</strong> ${{ github.repository }}</li>
                                <li><strong>Branch:</strong> ${{ github.ref_name }}</li>
                                <li><strong>Commit:</strong> ${{ github.sha }}</li>
                                <li><strong>Triggered by:</strong> ${{ github.actor }}</li>
                            </ul>
                        </div>
                        
                        <div style="text-align: center; margin: 30px 0;">
                            <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" 
                               style="display: inline-block; padding: 12px 24px; background-color: #c62828; color: white; text-decoration: none; border-radius: 6px; font-weight: bold;">
                                View Workflow Run
                            </a>
                        </div>
                        
                        <p style="font-size: 14px; color: #666; margin-top: 30px;">
                            Best regards,<br>
                            <strong>OpenCalc CI/CD Bot</strong>
                        </p>
                    </div>
                    
                    <div style="background-color: #f8f9fa; padding: 20px; text-align: center; border-top: 1px solid #eee;">
                        <p style="margin: 0; color: #888; font-size: 12px;">
                            <img src="https://cdn-icons-png.flaticon.com/512/5968/5968705.png" alt="Android" width="20" style="vertical-align: middle;"> 
                            Powered by GitHub Actions
                        </p>
                    </div>
                </div>
            </body>
            </html> 