name: Android CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Lint Check
        run: ./gradlew lint

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: app/build/reports/lint-results.html
          retention-days: 30

      - name: Send Lint Report Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "📊 Lint Report: OpenCalc CI/CD #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: OpenCalc CI/CD <amansingh08088@gmail.com>
          body: |
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
              <div style="background: linear-gradient(135deg, #2196F3, #1976D2); color: white; padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
                <h1 style="margin: 0; font-size: 24px;">📊 LINT REPORT</h1>
                <p style="margin: 10px 0 0 0; font-size: 16px;">Code Quality Analysis Results</p>
              </div>
              
              <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; border-left: 4px solid #2196F3;">
                <h2 style="color: #333; margin-top: 0;">📋 Analysis Summary</h2>
                <table style="width: 100%; border-collapse: collapse;">
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Repository:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.repository }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Branch:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.ref_name }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Commit:</td>
                    <td style="padding: 8px 0; color: #333; font-family: monospace;">${{ github.sha }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Build #:</td>
                    <td style="padding: 8px 0; color: #333;">#${{ github.run_number }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Triggered by:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.actor }}</td>
                  </tr>
                </table>
              </div>
              
              <div style="background: #e3f2fd; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #2196F3;">
                <h3 style="color: #1565c0; margin-top: 0;">🔍 What's Included</h3>
                <ul style="color: #1565c0; margin: 10px 0;">
                  <li>Code style violations and suggestions</li>
                  <li>Potential bugs and performance issues</li>
                  <li>Best practices recommendations</li>
                  <li>Security vulnerability checks</li>
                  <li>Accessibility improvements</li>
                </ul>
              </div>
              
              <div style="text-align: center; margin: 20px 0;">
                <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" 
                   style="background: #2196F3; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold;">
                  📊 View Full Lint Report
                </a>
              </div>
              
              <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin-top: 20px; text-align: center; color: #666; font-size: 14px;">
                <p style="margin: 0;">This is an automated lint report from OpenCalc CI/CD Pipeline</p>
                <p style="margin: 5px 0 0 0;">Generated on: ${{ github.event.head_commit.timestamp }}</p>
              </div>
            </div>
          attachments: app/build/reports/lint-results.html

  build:
    name: Build & Artifact Bundle
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      # --- Firebase App Distribution ---
      - name: Install Firebase CLI
        if: success()
        run: npm install -g firebase-tools

      - name: Upload AAB to Firebase App Distribution
        if: success()
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute app/build/outputs/bundle/release/app-release.aab \
            --app "1:111193224827:android:e8dba4f640d6014b3694de" \
            --release-notes "Automated build from CI: ${{ github.sha }}" \
            --groups "cicdtesters"

      # --- Email and Discord Notifications --

      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "🎉 BUILD SUCCESS: OpenCalc CI/CD #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: OpenCalc CI/CD <amansingh08088@gmail.com>
          body: |
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
              <div style="background: linear-gradient(135deg, #4CAF50, #45a049); color: white; padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
                <h1 style="margin: 0; font-size: 24px;">🎉 BUILD SUCCESSFUL</h1>
                <p style="margin: 10px 0 0 0; font-size: 16px;">OpenCalc CI/CD Pipeline Completed Successfully</p>
              </div>
              
              <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; border-left: 4px solid #4CAF50;">
                <h2 style="color: #333; margin-top: 0;">📋 Build Summary</h2>
                <table style="width: 100%; border-collapse: collapse;">
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Repository:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.repository }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Branch:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.ref_name }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Commit:</td>
                    <td style="padding: 8px 0; color: #333; font-family: monospace;">${{ github.sha }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Triggered by:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.actor }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Build #:</td>
                    <td style="padding: 8px 0; color: #333;">#${{ github.run_number }}</td>
                  </tr>
                </table>
              </div>
              
              <div style="background: #e8f5e8; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #4CAF50;">
                <h3 style="color: #2e7d32; margin-top: 0;">✅ What Happened</h3>
                <ul style="color: #2e7d32; margin: 10px 0;">
                  <li>Code quality checks passed</li>
                  <li>Android App Bundle (AAB) built successfully</li>
                  <li>App distributed to Firebase App Distribution</li>
                  <li>All artifacts uploaded and ready for deployment</li>
                </ul>
              </div>
              
              <div style="text-align: center; margin: 20px 0;">
                <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" 
                   style="background: #4CAF50; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold;">
                  📊 View Build Details
                </a>
              </div>
              
              <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin-top: 20px; text-align: center; color: #666; font-size: 14px;">
                <p style="margin: 0;">This is an automated notification from OpenCalc CI/CD Pipeline</p>
                <p style="margin: 5px 0 0 0;">Generated on: ${{ github.event.head_commit.timestamp }}</p>
              </div>
            </div>

      - name: Send Discord notification on success
        if: success()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🎉 **BUILD SUCCESSFUL** 🎉
            
            **OpenCalc CI/CD Pipeline** has completed successfully!
            
            📋 **Build Details:**
            • **Repository:** `${{ github.repository }}`
            • **Branch:** `${{ github.ref_name }}`
            • **Build #:** `#${{ github.run_number }}`
            • **Commit:** `${{ github.sha }}`
            • **Triggered by:** `${{ github.actor }}`
            
            ✅ **What was accomplished:**
            • Code quality checks passed
            • Android App Bundle (AAB) built successfully
            • App distributed to Firebase App Distribution
            • All artifacts uploaded and ready for deployment
            
            📊 **[View Full Build Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**
            
            ---
            *Automated notification from OpenCalc CI/CD Pipeline*

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: amansingh08088@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "🚨 BUILD FAILED: OpenCalc CI/CD #${{ github.run_number }}"
          to: amansingh08088@gmail.com
          from: OpenCalc CI/CD <amansingh08088@gmail.com>
          body: |
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
              <div style="background: linear-gradient(135deg, #f44336, #d32f2f); color: white; padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
                <h1 style="margin: 0; font-size: 24px;">🚨 BUILD FAILED</h1>
                <p style="margin: 10px 0 0 0; font-size: 16px;">OpenCalc CI/CD Pipeline Encountered Issues</p>
              </div>
              
              <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; border-left: 4px solid #f44336;">
                <h2 style="color: #333; margin-top: 0;">📋 Build Summary</h2>
                <table style="width: 100%; border-collapse: collapse;">
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Repository:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.repository }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Branch:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.ref_name }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Commit:</td>
                    <td style="padding: 8px 0; color: #333; font-family: monospace;">${{ github.sha }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Triggered by:</td>
                    <td style="padding: 8px 0; color: #333;">${{ github.actor }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555;">Build #:</td>
                    <td style="padding: 8px 0; color: #333;">#${{ github.run_number }}</td>
                  </tr>
                </table>
              </div>
              
              <div style="background: #ffebee; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #f44336;">
                <h3 style="color: #c62828; margin-top: 0;">⚠️ Action Required</h3>
                <ul style="color: #c62828; margin: 10px 0;">
                  <li>Review the build logs to identify the issue</li>
                  <li>Check for compilation errors or test failures</li>
                  <li>Verify all dependencies are properly configured</li>
                  <li>Ensure code quality standards are met</li>
                </ul>
              </div>
              
              <div style="text-align: center; margin: 20px 0;">
                <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" 
                   style="background: #f44336; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold;">
                  🔍 Investigate Build Failure
                </a>
              </div>
              
              <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin-top: 20px; text-align: center; color: #666; font-size: 14px;">
                <p style="margin: 0;">This is an automated notification from OpenCalc CI/CD Pipeline</p>
                <p style="margin: 5px 0 0 0;">Generated on: ${{ github.event.head_commit.timestamp }}</p>
              </div>
            </div>

      - name: Send Discord notification on failure
        if: failure()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🚨 **BUILD FAILED** 🚨
            
            **OpenCalc CI/CD Pipeline** has encountered issues!
            
            📋 **Build Details:**
            • **Repository:** `${{ github.repository }}`
            • **Branch:** `${{ github.ref_name }}`
            • **Build #:** `#${{ github.run_number }}`
            • **Commit:** `${{ github.sha }}`
            • **Triggered by:** `${{ github.actor }}`
            
            ⚠️ **Action Required:**
            • Review build logs to identify the issue
            • Check for compilation errors or test failures
            • Verify all dependencies are properly configured
            • Ensure code quality standards are met
            
            🔍 **[Investigate Build Failure](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**
            
            ---
            *Automated notification from OpenCalc CI/CD Pipeline*
